/home/mira/PycharmProjects/gp_plankton_model/train/train.py:132: DtypeWarning: Columns (64,65,130,131,188) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(train_config["data_path"])
Traceback (most recent call last):
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'log_syn_interpolated'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mira/PycharmProjects/gp_plankton_model/train/train.py", line 135, in <module>
    y = torch.tensor(df[config.dependent].values, dtype=torch.float32)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/mira/anaconda3/envs/pyro/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'log_syn_interpolated'